# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "admin.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_interface import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x61\x64min.proto\x12\x03\x65rp\x1a\x0c\x63ommon.proto"{\n\tSeedStats\x12\x11\n\tsuppliers\x18\x01 \x01(\x05\x12\x11\n\tmaterials\x18\x02 \x01(\x05\x12\x11\n\tcontracts\x18\x03 \x01(\x05\x12\x0e\n\x06orders\x18\x04 \x01(\x05\x12\x13\n\x0border_items\x18\x05 \x01(\x05\x12\x10\n\x08payments\x18\x06 \x01(\x05"\xcf\x01\n\x0bSeedRequest\x12\x1c\n\x0fsuppliers_count\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1c\n\x0fmaterials_count\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x19\n\x0corders_count\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x1c\n\x0f\x63ontracts_count\x18\x04 \x01(\x05H\x03\x88\x01\x01\x42\x12\n\x10_suppliers_countB\x12\n\x10_materials_countB\x0f\n\r_orders_countB\x12\n\x10_contracts_count"-\n\x0cSeedResponse\x12\x1d\n\x05stats\x18\x01 \x01(\x0b\x32\x0e.erp.SeedStats"1\n\x10GetStatsResponse\x12\x1d\n\x05stats\x18\x01 \x01(\x0b\x32\x0e.erp.SeedStats"1\n\rResetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xab\x01\n\x0c\x41\x64minService\x12\x33\n\x0cSeedDatabase\x12\x10.erp.SeedRequest\x1a\x11.erp.SeedResponse\x12/\n\rResetDatabase\x12\n.erp.Empty\x1a\x12.erp.ResetResponse\x12\x35\n\x10GetDatabaseStats\x12\n.erp.Empty\x1a\x15.erp.GetStatsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "admin_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SEEDSTATS"]._serialized_start = 34
    _globals["_SEEDSTATS"]._serialized_end = 157
    _globals["_SEEDREQUEST"]._serialized_start = 160
    _globals["_SEEDREQUEST"]._serialized_end = 367
    _globals["_SEEDRESPONSE"]._serialized_start = 369
    _globals["_SEEDRESPONSE"]._serialized_end = 414
    _globals["_GETSTATSRESPONSE"]._serialized_start = 416
    _globals["_GETSTATSRESPONSE"]._serialized_end = 465
    _globals["_RESETRESPONSE"]._serialized_start = 467
    _globals["_RESETRESPONSE"]._serialized_end = 516
    _globals["_ADMINSERVICE"]._serialized_start = 519
    _globals["_ADMINSERVICE"]._serialized_end = 690
# @@protoc_insertion_point(module_scope)
