# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import admin_pb2 as admin__pb2
from grpc_interface import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in admin_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AdminServiceStub(object):
    """Admin service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SeedDatabase = channel.unary_unary(
            "/erp.AdminService/SeedDatabase",
            request_serializer=admin__pb2.SeedRequest.SerializeToString,
            response_deserializer=admin__pb2.SeedResponse.FromString,
            _registered_method=True,
        )
        self.ResetDatabase = channel.unary_unary(
            "/erp.AdminService/ResetDatabase",
            request_serializer=common__pb2.Empty.SerializeToString,
            response_deserializer=admin__pb2.ResetResponse.FromString,
            _registered_method=True,
        )
        self.GetDatabaseStats = channel.unary_unary(
            "/erp.AdminService/GetDatabaseStats",
            request_serializer=common__pb2.Empty.SerializeToString,
            response_deserializer=admin__pb2.GetStatsResponse.FromString,
            _registered_method=True,
        )


class AdminServiceServicer(object):
    """Admin service"""

    def SeedDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResetDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDatabaseStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SeedDatabase": grpc.unary_unary_rpc_method_handler(
            servicer.SeedDatabase,
            request_deserializer=admin__pb2.SeedRequest.FromString,
            response_serializer=admin__pb2.SeedResponse.SerializeToString,
        ),
        "ResetDatabase": grpc.unary_unary_rpc_method_handler(
            servicer.ResetDatabase,
            request_deserializer=common__pb2.Empty.FromString,
            response_serializer=admin__pb2.ResetResponse.SerializeToString,
        ),
        "GetDatabaseStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetDatabaseStats,
            request_deserializer=common__pb2.Empty.FromString,
            response_serializer=admin__pb2.GetStatsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "erp.AdminService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("erp.AdminService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """Admin service"""

    @staticmethod
    def SeedDatabase(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.AdminService/SeedDatabase",
            admin__pb2.SeedRequest.SerializeToString,
            admin__pb2.SeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResetDatabase(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.AdminService/ResetDatabase",
            common__pb2.Empty.SerializeToString,
            admin__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDatabaseStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.AdminService/GetDatabaseStats",
            common__pb2.Empty.SerializeToString,
            admin__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
