# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import common_pb2 as common__pb2
from grpc_interface import contract_pb2 as contract__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in contract_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ContractServiceStub(object):
    """Contract service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContract = channel.unary_unary(
            "/erp.ContractService/GetContract",
            request_serializer=contract__pb2.GetContractRequest.SerializeToString,
            response_deserializer=contract__pb2.Contract.FromString,
            _registered_method=True,
        )
        self.CreateContract = channel.unary_unary(
            "/erp.ContractService/CreateContract",
            request_serializer=contract__pb2.CreateContractRequest.SerializeToString,
            response_deserializer=contract__pb2.Contract.FromString,
            _registered_method=True,
        )
        self.UpdateContract = channel.unary_unary(
            "/erp.ContractService/UpdateContract",
            request_serializer=contract__pb2.UpdateContractRequest.SerializeToString,
            response_deserializer=contract__pb2.Contract.FromString,
            _registered_method=True,
        )
        self.DeleteContract = channel.unary_unary(
            "/erp.ContractService/DeleteContract",
            request_serializer=contract__pb2.GetContractRequest.SerializeToString,
            response_deserializer=common__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.ListContracts = channel.unary_unary(
            "/erp.ContractService/ListContracts",
            request_serializer=contract__pb2.ListContractsRequest.SerializeToString,
            response_deserializer=contract__pb2.ListContractsResponse.FromString,
            _registered_method=True,
        )


class ContractServiceServicer(object):
    """Contract service"""

    def GetContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ContractServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetContract": grpc.unary_unary_rpc_method_handler(
            servicer.GetContract,
            request_deserializer=contract__pb2.GetContractRequest.FromString,
            response_serializer=contract__pb2.Contract.SerializeToString,
        ),
        "CreateContract": grpc.unary_unary_rpc_method_handler(
            servicer.CreateContract,
            request_deserializer=contract__pb2.CreateContractRequest.FromString,
            response_serializer=contract__pb2.Contract.SerializeToString,
        ),
        "UpdateContract": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateContract,
            request_deserializer=contract__pb2.UpdateContractRequest.FromString,
            response_serializer=contract__pb2.Contract.SerializeToString,
        ),
        "DeleteContract": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteContract,
            request_deserializer=contract__pb2.GetContractRequest.FromString,
            response_serializer=common__pb2.Empty.SerializeToString,
        ),
        "ListContracts": grpc.unary_unary_rpc_method_handler(
            servicer.ListContracts,
            request_deserializer=contract__pb2.ListContractsRequest.FromString,
            response_serializer=contract__pb2.ListContractsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "erp.ContractService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("erp.ContractService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ContractService(object):
    """Contract service"""

    @staticmethod
    def GetContract(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.ContractService/GetContract",
            contract__pb2.GetContractRequest.SerializeToString,
            contract__pb2.Contract.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateContract(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.ContractService/CreateContract",
            contract__pb2.CreateContractRequest.SerializeToString,
            contract__pb2.Contract.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateContract(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.ContractService/UpdateContract",
            contract__pb2.UpdateContractRequest.SerializeToString,
            contract__pb2.Contract.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteContract(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.ContractService/DeleteContract",
            contract__pb2.GetContractRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListContracts(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.ContractService/ListContracts",
            contract__pb2.ListContractsRequest.SerializeToString,
            contract__pb2.ListContractsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
