# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import common_pb2 as common__pb2
from grpc_interface import material_pb2 as material__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in material_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MaterialServiceStub(object):
    """Material service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMaterial = channel.unary_unary(
            "/erp.MaterialService/GetMaterial",
            request_serializer=material__pb2.GetMaterialRequest.SerializeToString,
            response_deserializer=material__pb2.Material.FromString,
            _registered_method=True,
        )
        self.CreateMaterial = channel.unary_unary(
            "/erp.MaterialService/CreateMaterial",
            request_serializer=material__pb2.CreateMaterialRequest.SerializeToString,
            response_deserializer=material__pb2.Material.FromString,
            _registered_method=True,
        )
        self.UpdateMaterial = channel.unary_unary(
            "/erp.MaterialService/UpdateMaterial",
            request_serializer=material__pb2.UpdateMaterialRequest.SerializeToString,
            response_deserializer=material__pb2.Material.FromString,
            _registered_method=True,
        )
        self.DeleteMaterial = channel.unary_unary(
            "/erp.MaterialService/DeleteMaterial",
            request_serializer=material__pb2.GetMaterialRequest.SerializeToString,
            response_deserializer=common__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.ListMaterials = channel.unary_unary(
            "/erp.MaterialService/ListMaterials",
            request_serializer=material__pb2.ListMaterialsRequest.SerializeToString,
            response_deserializer=material__pb2.ListMaterialsResponse.FromString,
            _registered_method=True,
        )


class MaterialServiceServicer(object):
    """Material service"""

    def GetMaterial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateMaterial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateMaterial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteMaterial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMaterials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MaterialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetMaterial": grpc.unary_unary_rpc_method_handler(
            servicer.GetMaterial,
            request_deserializer=material__pb2.GetMaterialRequest.FromString,
            response_serializer=material__pb2.Material.SerializeToString,
        ),
        "CreateMaterial": grpc.unary_unary_rpc_method_handler(
            servicer.CreateMaterial,
            request_deserializer=material__pb2.CreateMaterialRequest.FromString,
            response_serializer=material__pb2.Material.SerializeToString,
        ),
        "UpdateMaterial": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateMaterial,
            request_deserializer=material__pb2.UpdateMaterialRequest.FromString,
            response_serializer=material__pb2.Material.SerializeToString,
        ),
        "DeleteMaterial": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteMaterial,
            request_deserializer=material__pb2.GetMaterialRequest.FromString,
            response_serializer=common__pb2.Empty.SerializeToString,
        ),
        "ListMaterials": grpc.unary_unary_rpc_method_handler(
            servicer.ListMaterials,
            request_deserializer=material__pb2.ListMaterialsRequest.FromString,
            response_serializer=material__pb2.ListMaterialsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "erp.MaterialService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("erp.MaterialService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MaterialService(object):
    """Material service"""

    @staticmethod
    def GetMaterial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.MaterialService/GetMaterial",
            material__pb2.GetMaterialRequest.SerializeToString,
            material__pb2.Material.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateMaterial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.MaterialService/CreateMaterial",
            material__pb2.CreateMaterialRequest.SerializeToString,
            material__pb2.Material.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateMaterial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.MaterialService/UpdateMaterial",
            material__pb2.UpdateMaterialRequest.SerializeToString,
            material__pb2.Material.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteMaterial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.MaterialService/DeleteMaterial",
            material__pb2.GetMaterialRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMaterials(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.MaterialService/ListMaterials",
            material__pb2.ListMaterialsRequest.SerializeToString,
            material__pb2.ListMaterialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
