# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import common_pb2 as common__pb2
from grpc_interface import order_pb2 as order__pb2
from grpc_interface import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in order_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class OrderServiceStub(object):
    """Order service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrder = channel.unary_unary(
            "/erp.OrderService/GetOrder",
            request_serializer=order__pb2.GetOrderRequest.SerializeToString,
            response_deserializer=order__pb2.PurchaseOrder.FromString,
            _registered_method=True,
        )
        self.CreateOrder = channel.unary_unary(
            "/erp.OrderService/CreateOrder",
            request_serializer=order__pb2.CreateOrderRequest.SerializeToString,
            response_deserializer=order__pb2.PurchaseOrder.FromString,
            _registered_method=True,
        )
        self.UpdateOrder = channel.unary_unary(
            "/erp.OrderService/UpdateOrder",
            request_serializer=order__pb2.UpdateOrderRequest.SerializeToString,
            response_deserializer=order__pb2.PurchaseOrder.FromString,
            _registered_method=True,
        )
        self.DeleteOrder = channel.unary_unary(
            "/erp.OrderService/DeleteOrder",
            request_serializer=order__pb2.GetOrderRequest.SerializeToString,
            response_deserializer=common__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.ListOrders = channel.unary_unary(
            "/erp.OrderService/ListOrders",
            request_serializer=order__pb2.ListOrdersRequest.SerializeToString,
            response_deserializer=order__pb2.ListOrdersResponse.FromString,
            _registered_method=True,
        )
        self.GetOrderPayments = channel.unary_stream(
            "/erp.OrderService/GetOrderPayments",
            request_serializer=order__pb2.GetOrderPaymentsRequest.SerializeToString,
            response_deserializer=payment__pb2.Payment.FromString,
            _registered_method=True,
        )


class OrderServiceServicer(object):
    """Order service"""

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetOrderPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetOrder": grpc.unary_unary_rpc_method_handler(
            servicer.GetOrder,
            request_deserializer=order__pb2.GetOrderRequest.FromString,
            response_serializer=order__pb2.PurchaseOrder.SerializeToString,
        ),
        "CreateOrder": grpc.unary_unary_rpc_method_handler(
            servicer.CreateOrder,
            request_deserializer=order__pb2.CreateOrderRequest.FromString,
            response_serializer=order__pb2.PurchaseOrder.SerializeToString,
        ),
        "UpdateOrder": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateOrder,
            request_deserializer=order__pb2.UpdateOrderRequest.FromString,
            response_serializer=order__pb2.PurchaseOrder.SerializeToString,
        ),
        "DeleteOrder": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteOrder,
            request_deserializer=order__pb2.GetOrderRequest.FromString,
            response_serializer=common__pb2.Empty.SerializeToString,
        ),
        "ListOrders": grpc.unary_unary_rpc_method_handler(
            servicer.ListOrders,
            request_deserializer=order__pb2.ListOrdersRequest.FromString,
            response_serializer=order__pb2.ListOrdersResponse.SerializeToString,
        ),
        "GetOrderPayments": grpc.unary_stream_rpc_method_handler(
            servicer.GetOrderPayments,
            request_deserializer=order__pb2.GetOrderPaymentsRequest.FromString,
            response_serializer=payment__pb2.Payment.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "erp.OrderService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("erp.OrderService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Order service"""

    @staticmethod
    def GetOrder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.OrderService/GetOrder",
            order__pb2.GetOrderRequest.SerializeToString,
            order__pb2.PurchaseOrder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateOrder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.OrderService/CreateOrder",
            order__pb2.CreateOrderRequest.SerializeToString,
            order__pb2.PurchaseOrder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateOrder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.OrderService/UpdateOrder",
            order__pb2.UpdateOrderRequest.SerializeToString,
            order__pb2.PurchaseOrder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteOrder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.OrderService/DeleteOrder",
            order__pb2.GetOrderRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListOrders(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.OrderService/ListOrders",
            order__pb2.ListOrdersRequest.SerializeToString,
            order__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetOrderPayments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/erp.OrderService/GetOrderPayments",
            order__pb2.GetOrderPaymentsRequest.SerializeToString,
            payment__pb2.Payment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
