# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import common_pb2 as common__pb2
from grpc_interface import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in payment_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PaymentServiceStub(object):
    """Payment service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPayment = channel.unary_unary(
            "/erp.PaymentService/GetPayment",
            request_serializer=payment__pb2.GetPaymentRequest.SerializeToString,
            response_deserializer=payment__pb2.Payment.FromString,
            _registered_method=True,
        )
        self.CreatePayment = channel.unary_unary(
            "/erp.PaymentService/CreatePayment",
            request_serializer=payment__pb2.CreatePaymentRequest.SerializeToString,
            response_deserializer=payment__pb2.Payment.FromString,
            _registered_method=True,
        )
        self.UpdatePayment = channel.unary_unary(
            "/erp.PaymentService/UpdatePayment",
            request_serializer=payment__pb2.UpdatePaymentRequest.SerializeToString,
            response_deserializer=payment__pb2.Payment.FromString,
            _registered_method=True,
        )
        self.DeletePayment = channel.unary_unary(
            "/erp.PaymentService/DeletePayment",
            request_serializer=payment__pb2.GetPaymentRequest.SerializeToString,
            response_deserializer=common__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.ListPayments = channel.unary_unary(
            "/erp.PaymentService/ListPayments",
            request_serializer=payment__pb2.ListPaymentsRequest.SerializeToString,
            response_deserializer=payment__pb2.ListPaymentsResponse.FromString,
            _registered_method=True,
        )


class PaymentServiceServicer(object):
    """Payment service"""

    def GetPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeletePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetPayment": grpc.unary_unary_rpc_method_handler(
            servicer.GetPayment,
            request_deserializer=payment__pb2.GetPaymentRequest.FromString,
            response_serializer=payment__pb2.Payment.SerializeToString,
        ),
        "CreatePayment": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePayment,
            request_deserializer=payment__pb2.CreatePaymentRequest.FromString,
            response_serializer=payment__pb2.Payment.SerializeToString,
        ),
        "UpdatePayment": grpc.unary_unary_rpc_method_handler(
            servicer.UpdatePayment,
            request_deserializer=payment__pb2.UpdatePaymentRequest.FromString,
            response_serializer=payment__pb2.Payment.SerializeToString,
        ),
        "DeletePayment": grpc.unary_unary_rpc_method_handler(
            servicer.DeletePayment,
            request_deserializer=payment__pb2.GetPaymentRequest.FromString,
            response_serializer=common__pb2.Empty.SerializeToString,
        ),
        "ListPayments": grpc.unary_unary_rpc_method_handler(
            servicer.ListPayments,
            request_deserializer=payment__pb2.ListPaymentsRequest.FromString,
            response_serializer=payment__pb2.ListPaymentsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "erp.PaymentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("erp.PaymentService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Payment service"""

    @staticmethod
    def GetPayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.PaymentService/GetPayment",
            payment__pb2.GetPaymentRequest.SerializeToString,
            payment__pb2.Payment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreatePayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.PaymentService/CreatePayment",
            payment__pb2.CreatePaymentRequest.SerializeToString,
            payment__pb2.Payment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdatePayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.PaymentService/UpdatePayment",
            payment__pb2.UpdatePaymentRequest.SerializeToString,
            payment__pb2.Payment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeletePayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.PaymentService/DeletePayment",
            payment__pb2.GetPaymentRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPayments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.PaymentService/ListPayments",
            payment__pb2.ListPaymentsRequest.SerializeToString,
            payment__pb2.ListPaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
