# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import common_pb2 as common__pb2
from grpc_interface import supplier_pb2 as supplier__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in supplier_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SupplierServiceStub(object):
    """Supplier service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupplier = channel.unary_unary(
            "/erp.SupplierService/GetSupplier",
            request_serializer=supplier__pb2.GetSupplierRequest.SerializeToString,
            response_deserializer=supplier__pb2.Supplier.FromString,
            _registered_method=True,
        )
        self.CreateSupplier = channel.unary_unary(
            "/erp.SupplierService/CreateSupplier",
            request_serializer=supplier__pb2.CreateSupplierRequest.SerializeToString,
            response_deserializer=supplier__pb2.Supplier.FromString,
            _registered_method=True,
        )
        self.UpdateSupplier = channel.unary_unary(
            "/erp.SupplierService/UpdateSupplier",
            request_serializer=supplier__pb2.UpdateSupplierRequest.SerializeToString,
            response_deserializer=supplier__pb2.Supplier.FromString,
            _registered_method=True,
        )
        self.DeleteSupplier = channel.unary_unary(
            "/erp.SupplierService/DeleteSupplier",
            request_serializer=supplier__pb2.GetSupplierRequest.SerializeToString,
            response_deserializer=common__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.ListSuppliers = channel.unary_unary(
            "/erp.SupplierService/ListSuppliers",
            request_serializer=supplier__pb2.ListSuppliersRequest.SerializeToString,
            response_deserializer=supplier__pb2.ListSuppliersResponse.FromString,
            _registered_method=True,
        )


class SupplierServiceServicer(object):
    """Supplier service"""

    def GetSupplier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateSupplier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateSupplier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteSupplier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSuppliers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SupplierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSupplier": grpc.unary_unary_rpc_method_handler(
            servicer.GetSupplier,
            request_deserializer=supplier__pb2.GetSupplierRequest.FromString,
            response_serializer=supplier__pb2.Supplier.SerializeToString,
        ),
        "CreateSupplier": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSupplier,
            request_deserializer=supplier__pb2.CreateSupplierRequest.FromString,
            response_serializer=supplier__pb2.Supplier.SerializeToString,
        ),
        "UpdateSupplier": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateSupplier,
            request_deserializer=supplier__pb2.UpdateSupplierRequest.FromString,
            response_serializer=supplier__pb2.Supplier.SerializeToString,
        ),
        "DeleteSupplier": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSupplier,
            request_deserializer=supplier__pb2.GetSupplierRequest.FromString,
            response_serializer=common__pb2.Empty.SerializeToString,
        ),
        "ListSuppliers": grpc.unary_unary_rpc_method_handler(
            servicer.ListSuppliers,
            request_deserializer=supplier__pb2.ListSuppliersRequest.FromString,
            response_serializer=supplier__pb2.ListSuppliersResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "erp.SupplierService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("erp.SupplierService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SupplierService(object):
    """Supplier service"""

    @staticmethod
    def GetSupplier(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.SupplierService/GetSupplier",
            supplier__pb2.GetSupplierRequest.SerializeToString,
            supplier__pb2.Supplier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateSupplier(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.SupplierService/CreateSupplier",
            supplier__pb2.CreateSupplierRequest.SerializeToString,
            supplier__pb2.Supplier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateSupplier(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.SupplierService/UpdateSupplier",
            supplier__pb2.UpdateSupplierRequest.SerializeToString,
            supplier__pb2.Supplier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteSupplier(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.SupplierService/DeleteSupplier",
            supplier__pb2.GetSupplierRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListSuppliers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/erp.SupplierService/ListSuppliers",
            supplier__pb2.ListSuppliersRequest.SerializeToString,
            supplier__pb2.ListSuppliersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
