# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x0bwork_ticket\x1a\x0c\x63ommon.proto\"\x81\x01\n\x08Location\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07geo_ops\x18\x02 \x01(\t\x12\x11\n\tpx_region\x18\x03 \x01(\t\x12\x15\n\rpx_sub_region\x18\x04 \x01(\t\x12\x14\n\x0csub_region_1\x18\x05 \x01(\t\x12\x18\n\x10\x63ountry_name_ops\x18\x06 \x01(\t\" \n\x12GetLocationRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"Y\n\x14ListLocationsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x32\n\npagination\x18\x02 \x01(\x0b\x32\x1e.work_ticket.PaginationRequest\"r\n\x15ListLocationsResponse\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.work_ticket.Location\x12\x33\n\npagination\x18\x02 \x01(\x0b\x32\x1f.work_ticket.PaginationResponse2\xb4\x01\n\x0fLocationService\x12G\n\x0bGetLocation\x12\x1f.work_ticket.GetLocationRequest\x1a\x15.work_ticket.Location\"\x00\x12X\n\rListLocations\x12!.work_ticket.ListLocationsRequest\x1a\".work_ticket.ListLocationsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATION']._serialized_start=46
  _globals['_LOCATION']._serialized_end=175
  _globals['_GETLOCATIONREQUEST']._serialized_start=177
  _globals['_GETLOCATIONREQUEST']._serialized_end=209
  _globals['_LISTLOCATIONSREQUEST']._serialized_start=211
  _globals['_LISTLOCATIONSREQUEST']._serialized_end=300
  _globals['_LISTLOCATIONSRESPONSE']._serialized_start=302
  _globals['_LISTLOCATIONSRESPONSE']._serialized_end=416
  _globals['_LOCATIONSERVICE']._serialized_start=419
  _globals['_LOCATIONSERVICE']._serialized_end=599
# @@protoc_insertion_point(module_scope)
