# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import survey_pb2 as survey__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in survey_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SurveyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSurvey = channel.unary_unary(
                '/work_ticket.SurveyService/GetSurvey',
                request_serializer=survey__pb2.GetSurveyRequest.SerializeToString,
                response_deserializer=survey__pb2.Survey.FromString,
                _registered_method=True)
        self.ListSurveys = channel.unary_unary(
                '/work_ticket.SurveyService/ListSurveys',
                request_serializer=survey__pb2.ListSurveysRequest.SerializeToString,
                response_deserializer=survey__pb2.ListSurveysResponse.FromString,
                _registered_method=True)


class SurveyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSurvey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSurveys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SurveyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSurvey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSurvey,
                    request_deserializer=survey__pb2.GetSurveyRequest.FromString,
                    response_serializer=survey__pb2.Survey.SerializeToString,
            ),
            'ListSurveys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSurveys,
                    request_deserializer=survey__pb2.ListSurveysRequest.FromString,
                    response_serializer=survey__pb2.ListSurveysResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'work_ticket.SurveyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('work_ticket.SurveyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SurveyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSurvey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/work_ticket.SurveyService/GetSurvey',
            survey__pb2.GetSurveyRequest.SerializeToString,
            survey__pb2.Survey.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSurveys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/work_ticket.SurveyService/ListSurveys',
            survey__pb2.ListSurveysRequest.SerializeToString,
            survey__pb2.ListSurveysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
