# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: work_ticket.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'work_ticket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11work_ticket.proto\x12\x0bwork_ticket\x1a\x0c\x63ommon.proto\"\xe8\x01\n\nWorkTicket\x12\x12\n\nresponseid\x18\x01 \x01(\t\x12\x0c\n\x04osat\x18\x02 \x01(\x05\x12\x18\n\x10why_osat_en_mask\x18\x03 \x01(\t\x12\x1d\n\x15\x66irst_time_resolution\x18\x04 \x01(\x05\x12\x10\n\x08\x65\x61se_use\x18\x05 \x01(\x05\x12\x11\n\tsurvey_id\x18\x06 \x01(\x05\x12\x16\n\x0etime_period_id\x18\x07 \x01(\x05\x12\x13\n\x0blocation_id\x18\x08 \x01(\x05\x12\x12\n\nproduct_id\x18\t \x01(\x05\x12\x19\n\x11so_information_id\x18\n \x01(\x05\"*\n\x14GetWorkTicketRequest\x12\x12\n\nresponseid\x18\x01 \x01(\t\"[\n\x16ListWorkTicketsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x32\n\npagination\x18\x02 \x01(\x0b\x32\x1e.work_ticket.PaginationRequest\"v\n\x17ListWorkTicketsResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.work_ticket.WorkTicket\x12\x33\n\npagination\x18\x02 \x01(\x0b\x32\x1f.work_ticket.PaginationResponse2\xc2\x01\n\x11WorkTicketService\x12M\n\rGetWorkTicket\x12!.work_ticket.GetWorkTicketRequest\x1a\x17.work_ticket.WorkTicket\"\x00\x12^\n\x0fListWorkTickets\x12#.work_ticket.ListWorkTicketsRequest\x1a$.work_ticket.ListWorkTicketsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'work_ticket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKTICKET']._serialized_start=49
  _globals['_WORKTICKET']._serialized_end=281
  _globals['_GETWORKTICKETREQUEST']._serialized_start=283
  _globals['_GETWORKTICKETREQUEST']._serialized_end=325
  _globals['_LISTWORKTICKETSREQUEST']._serialized_start=327
  _globals['_LISTWORKTICKETSREQUEST']._serialized_end=418
  _globals['_LISTWORKTICKETSRESPONSE']._serialized_start=420
  _globals['_LISTWORKTICKETSRESPONSE']._serialized_end=538
  _globals['_WORKTICKETSERVICE']._serialized_start=541
  _globals['_WORKTICKETSERVICE']._serialized_end=735
# @@protoc_insertion_point(module_scope)
