"""change_label_to_jsonb

Revision ID: 80a7d5ebda72
Revises: 42f9341fffbc
Create Date: 2026-02-09 23:56:12.062579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80a7d5ebda72"
down_revision: Union[str, Sequence[str], None] = "42f9341fffbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schema_classes",
        "label",
        existing_type=sa.VARCHAR(length=500),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="jsonb_build_array(label)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schema_classes",
        "label",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
