# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x0bwork_ticket\x1a\x0c\x63ommon.proto\"{\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tbrand_ops\x18\x02 \x01(\t\x12\x19\n\x11product_group_ops\x18\x03 \x01(\t\x12\x16\n\x0eproduct_series\x18\x04 \x01(\t\x12\x1e\n\x16machine_type_4_digital\x18\x05 \x01(\t\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"X\n\x13ListProductsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x32\n\npagination\x18\x02 \x01(\x0b\x32\x1e.work_ticket.PaginationRequest\"p\n\x14ListProductsResponse\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.work_ticket.Product\x12\x33\n\npagination\x18\x02 \x01(\x0b\x32\x1f.work_ticket.PaginationResponse2\xad\x01\n\x0eProductService\x12\x44\n\nGetProduct\x12\x1e.work_ticket.GetProductRequest\x1a\x14.work_ticket.Product\"\x00\x12U\n\x0cListProducts\x12 .work_ticket.ListProductsRequest\x1a!.work_ticket.ListProductsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=44
  _globals['_PRODUCT']._serialized_end=167
  _globals['_GETPRODUCTREQUEST']._serialized_start=169
  _globals['_GETPRODUCTREQUEST']._serialized_end=200
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=202
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=290
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=292
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=404
  _globals['_PRODUCTSERVICE']._serialized_start=407
  _globals['_PRODUCTSERVICE']._serialized_end=580
# @@protoc_insertion_point(module_scope)
