# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import so_information_pb2 as so__information__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in so_information_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SOInformationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSOInformation = channel.unary_unary(
                '/work_ticket.SOInformationService/GetSOInformation',
                request_serializer=so__information__pb2.GetSOInformationRequest.SerializeToString,
                response_deserializer=so__information__pb2.SOInformation.FromString,
                _registered_method=True)
        self.ListSOInformations = channel.unary_unary(
                '/work_ticket.SOInformationService/ListSOInformations',
                request_serializer=so__information__pb2.ListSOInformationsRequest.SerializeToString,
                response_deserializer=so__information__pb2.ListSOInformationsResponse.FromString,
                _registered_method=True)


class SOInformationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSOInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSOInformations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SOInformationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSOInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSOInformation,
                    request_deserializer=so__information__pb2.GetSOInformationRequest.FromString,
                    response_serializer=so__information__pb2.SOInformation.SerializeToString,
            ),
            'ListSOInformations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSOInformations,
                    request_deserializer=so__information__pb2.ListSOInformationsRequest.FromString,
                    response_serializer=so__information__pb2.ListSOInformationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'work_ticket.SOInformationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('work_ticket.SOInformationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SOInformationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSOInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/work_ticket.SOInformationService/GetSOInformation',
            so__information__pb2.GetSOInformationRequest.SerializeToString,
            so__information__pb2.SOInformation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSOInformations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/work_ticket.SOInformationService/ListSOInformations',
            so__information__pb2.ListSOInformationsRequest.SerializeToString,
            so__information__pb2.ListSOInformationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
